//! Runtime owner-scoped Texture identity catalog for Robots.
//!
//! The corpus catalog is generated by `eurochef-cli edb texture-alias-report`.
//! Local Texture UIDs are never treated as globally unique: every lookup is keyed
//! by `(owner EDB UID, serialized Texture UID)`. The catalog adds exact decoded-
//! content group identity (`TXGxxxxx`) and, only where proven unambiguous, a
//! recovered global Texture UID/name.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    sync::{Arc, OnceLock, RwLock},
};

use anyhow::{bail, Context, Result};

use crate::Hashcode;

pub const OWNER_CATALOG_FILENAME: &str = "ROBOTS_TEXTURE_OWNER_CATALOG.tsv";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TextureIdentityRecord {
    pub owner_edb_uid: Hashcode,
    pub owner_edb_label: String,
    pub owner_edb_path: String,
    pub texture_index: usize,
    pub texture_uid: Hashcode,
    pub serialized_label: String,
    pub exact_group: String,
    pub exact_group_size: usize,
    pub alias_status: String,
    pub recovered_global_uid: Option<Hashcode>,
    pub recovered_global_label: Option<String>,
}

#[derive(Debug, Clone, Default)]
pub struct TextureIdentityCatalog {
    source_path: Option<PathBuf>,
    records: BTreeMap<(Hashcode, Hashcode), TextureIdentityRecord>,
}

static ACTIVE_CATALOG: OnceLock<RwLock<Option<Arc<TextureIdentityCatalog>>>> = OnceLock::new();

impl TextureIdentityCatalog {
    pub fn load(path: &Path) -> Result<Self> {
        let text = fs::read_to_string(path)
            .with_context(|| format!("read Texture identity catalog {}", path.display()))?;
        let mut lines = text.lines();
        let header = lines.next().context("Texture identity catalog is empty")?;
        let columns = header
            .split('\t')
            .enumerate()
            .map(|(index, name)| (name.trim(), index))
            .collect::<BTreeMap<_, _>>();

        let required = [
            "owner_edb_uid",
            "owner_edb_label",
            "owner_edb_path",
            "texture_index",
            "texture_uid",
            "serialized_label",
            "exact_group",
            "exact_group_size",
            "alias_status",
            "recovered_global_uid",
            "recovered_global_label",
        ];
        for name in required {
            if !columns.contains_key(name) {
                bail!(
                    "Texture identity catalog {} is missing column {name}",
                    path.display()
                );
            }
        }

        let mut records = BTreeMap::new();
        for (line_index, line) in lines.enumerate() {
            if line.trim().is_empty() {
                continue;
            }
            let fields = line.split('\t').collect::<Vec<_>>();
            let field = |name: &str| -> Result<&str> {
                let index = *columns
                    .get(name)
                    .with_context(|| format!("missing column {name}"))?;
                fields.get(index).copied().with_context(|| {
                    format!(
                        "Texture identity catalog {} line {} is missing field {name}",
                        path.display(),
                        line_index + 2
                    )
                })
            };

            let owner_edb_uid = parse_uid(field("owner_edb_uid")?)?;
            let texture_uid = parse_uid(field("texture_uid")?)?;
            let exact_group = field("exact_group")?.trim().to_string();
            if exact_group.is_empty() {
                bail!(
                    "Texture identity catalog {} line {} has empty exact_group",
                    path.display(),
                    line_index + 2
                );
            }
            let recovered_global_uid = parse_optional_uid(field("recovered_global_uid")?)?;
            let recovered_global_label = nonempty(field("recovered_global_label")?);
            let record = TextureIdentityRecord {
                owner_edb_uid,
                owner_edb_label: field("owner_edb_label")?.to_string(),
                owner_edb_path: field("owner_edb_path")?.to_string(),
                texture_index: field("texture_index")?.parse().with_context(|| {
                    format!(
                        "invalid texture_index on line {} of {}",
                        line_index + 2,
                        path.display()
                    )
                })?,
                texture_uid,
                serialized_label: field("serialized_label")?.to_string(),
                exact_group,
                exact_group_size: field("exact_group_size")?.parse().with_context(|| {
                    format!(
                        "invalid exact_group_size on line {} of {}",
                        line_index + 2,
                        path.display()
                    )
                })?,
                alias_status: field("alias_status")?.to_string(),
                recovered_global_uid,
                recovered_global_label,
            };
            let key = (owner_edb_uid, texture_uid);
            if let Some(previous) = records.insert(key, record.clone()) {
                if previous != record {
                    bail!(
                        "Texture identity catalog {} contains conflicting owner/local key 0x{owner_edb_uid:08X}:0x{texture_uid:08X}",
                        path.display()
                    );
                }
            }
        }

        Ok(Self {
            source_path: Some(path.to_path_buf()),
            records,
        })
    }

    pub fn get(
        &self,
        owner_edb_uid: Hashcode,
        texture_uid: Hashcode,
    ) -> Option<&TextureIdentityRecord> {
        self.records.get(&(owner_edb_uid, texture_uid))
    }

    pub fn len(&self) -> usize {
        self.records.len()
    }

    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }

    pub fn source_path(&self) -> Option<&Path> {
        self.source_path.as_deref()
    }
}

pub fn discover_catalog_path(source_path: &Path) -> Option<PathBuf> {
    if let Some(explicit) = std::env::var_os("EUROCHEF_TEXTURE_IDENTITY_CATALOG") {
        let explicit = PathBuf::from(explicit);
        if explicit.is_file() {
            return Some(explicit);
        }
    }

    for ancestor in source_path.ancestors() {
        if ancestor
            .file_name()
            .is_some_and(|name| name == "_eurotools_out")
        {
            let candidate = ancestor
                .join("research")
                .join("texture_identity")
                .join(OWNER_CATALOG_FILENAME);
            if candidate.is_file() {
                return Some(candidate);
            }
        }

        let candidate = ancestor
            .join("_eurotools_out")
            .join("research")
            .join("texture_identity")
            .join(OWNER_CATALOG_FILENAME);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

pub fn install_discovered(source_path: &Path) -> Result<Option<PathBuf>> {
    let path = discover_catalog_path(source_path);
    let lock = ACTIVE_CATALOG.get_or_init(|| RwLock::new(None));
    let mut active = lock
        .write()
        .expect("Texture identity catalog lock poisoned");
    match path {
        Some(path) => {
            let already_loaded = active
                .as_ref()
                .and_then(|catalog| catalog.source_path())
                .is_some_and(|loaded| loaded == path);
            if !already_loaded {
                *active = Some(Arc::new(TextureIdentityCatalog::load(&path)?));
            }
            Ok(Some(path))
        }
        None => {
            *active = None;
            Ok(None)
        }
    }
}

pub fn install(catalog: TextureIdentityCatalog) {
    let lock = ACTIVE_CATALOG.get_or_init(|| RwLock::new(None));
    *lock
        .write()
        .expect("Texture identity catalog lock poisoned") = Some(Arc::new(catalog));
}

pub fn clear() {
    let lock = ACTIVE_CATALOG.get_or_init(|| RwLock::new(None));
    *lock
        .write()
        .expect("Texture identity catalog lock poisoned") = None;
}

pub fn active_catalog_path() -> Option<PathBuf> {
    let lock = ACTIVE_CATALOG.get_or_init(|| RwLock::new(None));
    lock.read()
        .expect("Texture identity catalog lock poisoned")
        .as_ref()
        .and_then(|catalog| catalog.source_path().map(Path::to_path_buf))
}

pub fn active_record(
    owner_edb_uid: Hashcode,
    texture_uid: Hashcode,
) -> Option<TextureIdentityRecord> {
    let lock = ACTIVE_CATALOG.get_or_init(|| RwLock::new(None));
    lock.read()
        .expect("Texture identity catalog lock poisoned")
        .as_ref()
        .and_then(|catalog| catalog.get(owner_edb_uid, texture_uid).cloned())
}

pub fn resolve_global(owner_edb_uid: Hashcode, texture_uid: Hashcode) -> Option<Hashcode> {
    active_record(owner_edb_uid, texture_uid).and_then(|record| record.recovered_global_uid)
}

fn parse_uid(value: &str) -> Result<Hashcode> {
    let trimmed = value.trim();
    let hex = trimmed
        .strip_prefix("0x")
        .or_else(|| trimmed.strip_prefix("0X"))
        .unwrap_or(trimmed);
    u32::from_str_radix(hex, 16).with_context(|| format!("invalid UID {value}"))
}

fn parse_optional_uid(value: &str) -> Result<Option<Hashcode>> {
    if value.trim().is_empty() {
        Ok(None)
    } else {
        parse_uid(value).map(Some)
    }
}

fn nonempty(value: &str) -> Option<String> {
    let value = value.trim();
    (!value.is_empty()).then(|| value.to_string())
}

#[cfg(test)]
mod tests {
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;

    #[test]
    fn owner_local_identity_is_loaded_without_global_uid_guessing() {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "eurochef-texture-identity-{}-{nonce}",
            std::process::id()
        ));
        fs::create_dir_all(&root).unwrap();
        let path = root.join(OWNER_CATALOG_FILENAME);
        fs::write(
            &path,
            concat!(
                "owner_edb_uid\towner_edb_label\towner_edb_path\ttexture_index\ttexture_uid\tserialized_label\tscope\tfingerprint_fnv64\texact_group\texact_group_size\texact_local_count\texact_global_count\talias_status\trecovered_global_uid\trecovered_global_label\n",
                "0x01000071\tm03_hub1.edb\tC:/Robots/m03_hub1.edb\t215\t0x860000D7\tHT_Local_Texture_860000D7\tlocal\t1234\tTXG00001\t8\t7\t1\tlocal_exact_global_alias\t0x06000010\tHT_Texture_BlankWhite\n",
                "0x01000071\tm03_hub1.edb\tC:/Robots/m03_hub1.edb\t314\t0x8600013A\tHT_Local_Texture_8600013A\tlocal\t5678\tTXG00002\t3\t3\t0\tlocal_exact_duplicate\t\t\n"
            ),
        )
        .unwrap();

        let catalog = TextureIdentityCatalog::load(&path).unwrap();
        assert_eq!(catalog.len(), 2);
        let named = catalog.get(0x0100_0071, 0x8600_00D7).unwrap();
        assert_eq!(named.exact_group, "TXG00001");
        assert_eq!(named.recovered_global_uid, Some(0x0600_0010));
        let unnamed = catalog.get(0x0100_0071, 0x8600_013A).unwrap();
        assert_eq!(unnamed.exact_group, "TXG00002");
        assert_eq!(unnamed.recovered_global_uid, None);
        assert!(catalog.get(0x0100_0012, 0x8600_00D7).is_none());

        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn configured_real_robots_catalog_resolves_owner_scoped_texture_identity() {
        let Ok(game_root) = std::env::var("EUROCHEF_ROBOTS_GAME_ROOT") else {
            return;
        };
        let game_root = PathBuf::from(game_root);
        let representative_source = game_root
            .join("_eurotools_out")
            .join("extracted_main")
            .join("robots")
            .join("binary")
            .join("_bin_pc")
            .join("m03_hub1.edb");
        let path = discover_catalog_path(&representative_source)
            .expect("real Robots Texture identity catalog was not discovered");
        let catalog = TextureIdentityCatalog::load(&path).unwrap();
        assert_eq!(catalog.len(), 3963);

        let blank = catalog.get(0x0100_0071, 0x8600_00D7).unwrap();
        assert_eq!(blank.recovered_global_uid, Some(0x0600_0010));
        assert!(!blank.exact_group.is_empty());

        let owner_local = catalog.get(0x0100_0071, 0x8600_013A).unwrap();
        assert_eq!(owner_local.recovered_global_uid, None);
        assert!(!owner_local.exact_group.is_empty());
    }
}
